name: Update Version and Tag
#test
on:
  push:
    branches:
      - Basic-Utility
      - main

jobs:
  update-version:
    runs-on: ubuntu-latest

    steps:
      # Checkout repozytorium
      - name: Checkout code
        uses: actions/checkout@v3

      # Pobierz aktualną wersję z pom.xml
      - name: Get current version
        id: get-version
        run: |
          VERSION=$(grep -oPm1 "(?<=<version>)[^<]+" pom.xml)
          echo "Current version: $VERSION"
          echo "version=$VERSION" >> $GITHUB_ENV

      # Inkrementacja wersji (patch version)
      - name: Increment version
        id: increment-version
        run: |
          OLD_VERSION=$(echo "${{ env.version }}")
          NEW_VERSION=$(echo "$OLD_VERSION" | awk -F. -v OFS=. '{$NF++; print}')
          echo "New version: $NEW_VERSION"
          echo "new_version=$NEW_VERSION" >> $GITHUB_ENV

      # Zaktualizuj wersję w pom.xml
      - name: Update pom.xml with new version
        run: |
          sed -i "s|<version>${{ env.version }}</version>|<version>${{ env.new_version }}</version>|g" pom.xml
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add pom.xml
          git commit -m "Update version to ${{ env.new_version }}"

      # Wypchnij zmiany do repozytorium
      - name: Push changes
        run: git push origin main

      # Utwórz tag dla nowej wersji
      - name: Create a new tag
        run: |
          git tag -a "v${{ env.new_version }}" -m "Release version ${{ env.new_version }}"
          git push origin "v${{ env.new_version }}"
