name: Update Version and Tag and Release

on:
  push:
    branches:
      - Basic-Utility
      - main

jobs:
  update-version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get current version
        id: get-version
        run: |
          # Wydobądź wersję z pom.xml (np. "0.1" → "0.1.0")
          VERSION=$(grep -oPm1 "(?<=<version>)[^<]+" pom.xml)
          echo "Current version: $VERSION"
          
          # Dodaj trzeci segment (Z), jeśli go brakuje (np. "0.1" → "0.1.0")
          if [[ "$VERSION" =~ ^[0-9]+\.[0-9]+$ ]]; then
            VERSION="$VERSION.0"
          fi
          
          echo "version=$VERSION" >> $GITHUB_ENV

      - name: Increment version (X.Y.Z)
        id: increment-version
        run: |
          OLD_VERSION=$(echo "${{ env.version }}")
          IFS='.' read -r -a VERSION_PARTS <<< "$OLD_VERSION"
          
          MAJOR=${VERSION_PARTS[0]}
          MINOR=${VERSION_PARTS[1]}
          PATCH=${VERSION_PARTS[2]}
          
          # Inkrementuj PATCH (Z)
          PATCH=$((PATCH + 1))
          NEW_VERSION="$MAJOR.$MINOR.$PATCH"
          
          echo "New version: $NEW_VERSION"
          echo "new_version=$NEW_VERSION" >> $GITHUB_ENV

      - name: Debug version
        run: |
          echo "Current version: ${{ env.version }}"
          echo "New version: ${{ env.new_version }}"

      - name: Update pom.xml with new version
        run: |
          # Zamień starą wersję na nową (np. "0.1" → "0.1.1")
          sed -i "s|<version>${{ env.version }}</version>|<version>${{ env.new_version }}</version>|g" pom.xml
          
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add pom.xml
          git commit -m "Update version to ${{ env.new_version }}"

      - name: Pull latest changes
        run: |
          git pull --rebase origin main

      - name: Push changes
        run: |
          git push origin main

      - name: Create a new tag (vX.Y.Z)
        run: |
          git tag -a "v${{ env.new_version }}" -m "Release version ${{ env.new_version }}"
          git push origin "v${{ env.new_version }}"

      - name: Build application
        run: mvn clean package

      - name: Move artifact
        run: |
          mkdir -p artifacts
          cp target/*.jar artifacts/

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: spring-boot-app
          path: artifacts/

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: "v${{ env.new_version }}"
          name: "Release v${{ env.new_version }}"
          body: "Automatyczne wydanie wersji ${{ env.new_version }}"
          files: artifacts/*.jar
